SELECT SUM(CITY.POPULATION)
FROM CITY , COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE
  AND COUNTRY.CONTINENT = 'Asia';

SELECT SUM(city.POPULATION)
FROM CITY INNER JOIN COUNTRY
    ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Asia';