SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MEMBER_PROFILE.GENDER = "W" AND MONTH(MEMBER_PROFILE.DATE_OF_BIRTH) = "03" AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC