SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.SCORE
FROM REST_INFO AS I, (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS R
WHERE I.REST_ID = R.REST_ID AND ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC