SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, (
    SELECT T.ITEM_ID
    FROM ITEM_TREE AS T, ITEM_INFO AS I
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID AND I.RARITY = "RARE") AS P
WHERE I.ITEM_ID = P.ITEM_ID
ORDER BY ITEM_ID DESC