SELECT DATE_FORMAT(t.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, t.PRODUCT_ID, t.USER_ID, t.SALES_AMOUNT
FROM
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE) AS t
WHERE LEFT(SALES_DATE, 7) = "2022-03"
ORDER BY t.SALES_DATE ASC, t.PRODUCT_ID ASC, t.USER_ID ASC