SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY AS R, (
    SELECT BOARD_ID, TITLE
    FROM USED_GOODS_BOARD
    WHERE CREATED_DATE LIKE "2022-10%"
) AS B
WHERE R.BOARD_ID = B.BOARD_ID
ORDER BY CREATED_DATE ASC, TITLE ASC