SELECT D.DEPT_ID, D.DEPT_NAME_EN, S.AVG_SAL
FROM HR_DEPARTMENT AS D, (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID ) AS S
WHERE D.DEPT_ID = S.DEPT_ID
ORDER BY AVG_SAL DESC