SELECT S.SUM_SCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E,  (
    SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SUM_SCORE DESC
    LIMIT 1
) AS S
WHERE E.EMP_NO = S.EMP_NO