SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (
    SELECT MAX(VIEWS) FROM USED_GOODS_BOARD
)
ORDER BY F.FILE_ID DESC