SELECT I.ID,
       N.FISH_NAME,
       I.LENGTH
FROM (SELECT *, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) R
      FROM FISH_INFO ) I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.R = 1
ORDER BY I.ID