SELECT HACKER_ID, NAME, CHALLENGES_CREATED
FROM
    (SELECT H.HACKER_ID,H.NAME,CHALLENGES_CREATED,
            MAX(CHALLENGES_CREATED) OVER (ORDER BY 1) AS MX_CHLNG, -- CHALLENGES_CREATED의 최댓값 추출
            COUNT(CHALLENGES_CREATED) OVER(PARTITION BY CHALLENGES_CREATED) AS NO_OF_COMMON_CHLNG_HCKR -- 이 값이 1이면 해당 문제 수를 푼 사람은 한 명이라는 것
     FROM HACKERS H -- 아래 조인 절에서 해커가 도전한 챌린지 수를 테이블로 생성(CHALLENGES_CREATED)
     JOIN (
        SELECT DISTINCT HACKER_ID, COUNT(CHALLENGE_ID) OVER (PARTITION BY HACKER_ID) AS CHALLENGES_CREATED
        FROM CHALLENGES) C
     ON H.HACKER_ID=C.HACKER_ID
     )A
WHERE NO_OF_COMMON_CHLNG_HCKR=1
   OR (CHALLENGES_CREATED>=MX_CHLNG AND NO_OF_COMMON_CHLNG_HCKR!=1)
ORDER BY CHALLENGES_CREATED DESC, HACKER_ID ASC
;