SELECT DISTINCT HACKER_ID, NAME, SUM(MAX_SCORE) AS TOTAL_SCORE
FROM
    (SELECT S.HACKER_ID,H.NAME,S.CHALLENGE_ID,MAX(S.SCORE) AS MAX_SCORE
    FROM HACKERS H
    JOIN SUBMISSIONS S
    ON H.HACKER_ID = S.HACKER_ID
    WHERE S.SCORE > 0
    GROUP BY S.HACKER_ID, H.NAME, S.CHALLENGE_ID)
GROUP BY HACKER_ID, NAME
ORDER BY TOTAL_SCORE DESC, HACKER_ID ASC;